# Welcome to my Ultimate Plex Stack! (Modernized Fork)
#
# Make sure to rename this file to "docker-compose.yaml" if you are using git clone
#
# This is a modernized version of the original ultimate-plex-stack
# Updated to use current tools and replace deprecated ones (2025/2026)
#
# Environment Variable Examples:
# PUID = 99
# GUID = 101
# TZ = America/Edmonton
# BASE_PATH = /home/username/docker
#
# https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/ # This can be useful for establishing how the media will be presented below
# MEDIA_SHARE = /mnt/media   # This can also be renamed to "SHARE" or "MEDIA" this is where you will present your media
#
# NOTE: This is not a plug and play solution, some research / customization will be required to make this work as intended
# Feel free to customize ie: remove/change/add containers as needed - one size does not fit all

---
version: "3.0"

networks: #This is used if you have a reverse proxy. I use Nginx Proxy Manager but anything will do
  proxy: #You can remove this block if you are not planning to use a vpn
    external:
      name: proxy

services:
  #Plex - used to display the media
  #
  #This can also be replaced by Emby/Jellyfin
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    devices:
     - /dev/dri:/dev/dri #Required for plex HW transcoding / QuickSync
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_SHARE}/media/tv:/tv
      - ${MEDIA_SHARE}/media/movies:/movies
    restart: unless-stopped

  #Radarr - used to find movies automatically
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${MEDIA_SHARE}:/share #Access to the entire share
    #networks: #Does not connect to seerr if you use NPM
    #  - proxy
    ports:
      - 7878:7878
    restart: unless-stopped

  #Sonarr - used to find tv shows automatically
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${MEDIA_SHARE}:/share #Access to the entire share
    #networks: #Does not connect to seerr if you use NPM
    #  - proxy
    ports:
      - 8989:8989
    restart: unless-stopped

  #Readarr - Used to download books
  #
  #NOTE: DISABLED - LinuxServer image deprecated and no amd64 support available
  #TODO: Find alternative or wait for upstream fix
  #readarr:
  #  image: linuxserver/readarr:develop
  #  container_name: readarr
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${GUID}
  #    - TZ=${TZ}
  #  volumes:
  #    - ${BASE_PATH}/readarr/config:/config
  #    - ${MEDIA_SHARE}:/share
  #  ports:
  #    - 8787:8787
  #  restart: unless-stopped

  #Lidarr - Used to download music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/lidarr/config:/config
      - ${MEDIA_SHARE}:/share
    ports:
      - 8686:8686
    restart: unless-stopped

  #Prowlarr - manages your Sonarr, Radarr and download client
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr/config:/config
    #networks:
    #  - proxy
    ports:
      - 9696:9696
    restart: unless-stopped

  #Autobrr - used to grab torrents using the trackers IRC channel - Increases seeding due to grabbing content before RSS feed
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${GUID}
    volumes:
      - ${BASE_PATH}/autobrr/config:/config
    ports:
      - 7474:7474

  #Seerr - allows users to request media on their own
  #
  #UPDATED: Replaces Overseerr. Seerr is the unified successor to Overseerr and Jellyseerr
  #Supports Plex, Jellyfin, and Emby
  #Note: Using develop tag until stable release is available
  #Migration guide: https://docs.seerr.dev/
  seerr:
    image: ghcr.io/seerr-team/seerr:develop
    container_name: seerr
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/seerr/config:/app/config
    #networks:
    #  - proxy
    ports:
      - 5055:5055
    restart: unless-stopped

  #Byparr - Used as a proxy server to bypass Cloudflare and DDoS-GUARD protection
  #
  #UPDATED: Replaces Flaresolverr. Byparr is a modern drop-in replacement using Camoufox
  #Uses the same API as Flaresolverr, so no changes needed in Prowlarr config
  #https://github.com/ThePhaseless/Byparr
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  #Qbittorrent - torrenting software
  #
  #You can also use RuTorrent, Transmission or Deluge
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8694 #Make sure to port forward this port in your router so you can seed more effectively
    volumes:
      - ${BASE_PATH}/qbittorrent/config:/config
      - ${MEDIA_SHARE}:/share
    restart: unless-stopped

  #Tautulli - for plex statistics. Very useful when troubleshooting performance issues
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/tautulli:/config
    networks:
      - proxy
    ports:
      - 8181:8181
    restart: unless-stopped

  #Tdarr - to transcode videos from one format to another like x265 or H.265
  #
  #This container requires a decent amount of horse power to run but will save space in the long run
  #Alternative open-source option: Unmanic (https://github.com/Unmanic/unmanic)
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${GUID}
      - UMASK_SET=002
      - nodeName=ServerNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ${BASE_PATH}/tdarr/server:/app/server
      - ${BASE_PATH}/tdarr/configs:/app/configs
      - ${BASE_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_SHARE}:/media
      - /transcode_cache:/temp
    devices:
     - /dev/dri:/dev/dri #Required for HW transcoding / QuickSync

  #Membarr - to invite users via discord
  #
  #DISABLED - Using Wizarr instead
  #membarr:
  #  container_name: membarr
  #  image: yoruio/membarr:latest
  #  restart: unless-stopped
  #  environment:
  #    - token=${MEMBARR_TOKEN}
  #  volumes:
  #    - ${BASE_PATH}/membarr/config:/app/app/config

  #Bazarr - for subtitles. Try to use SRT format if you can rather than PGS due to performance issues
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr/config:/config
      - ${MEDIA_SHARE}:/share
    ports:
      - 6767:6767

  #Plex Auto Languages - This switches languages automatically example: watching english show and non english speaks you get subtitle
  #
  #UPDATED: Using JourneyOver fork which is actively maintained
  #Alternative: thesammykins TypeScript rewrite (https://github.com/thesammykins/plex-auto-languages)
  plexautolanguages:
    image: journeyover/plex-auto-languages:latest
    container_name: plex-auto-languages
    environment:
      - PLEX_URL=${PLEX_URL} #This is your local URL example: http://192.168.1.10:32400
      #To find your plex token go to https://app.plex.tv/, go to your library, click on the 3 dots on the bottom right of one of your tv/movie posters
      #Then click "View XML" in the bottom right of that popup, look at the URL of the XML window and find your X-Plex-Token= in the URL (at the very end)
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/pal/config:/config
    restart: unless-stopped

  #Cross Seed - used to take torrents from one tracker and seed them on another without leeching first. Increases ratio
  #
  #DISABLED - Requires advanced configuration
  #cross-seed:
  #  image: ghcr.io/cross-seed/cross-seed:6
  #  container_name: cross-seed
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${GUID}
  #  ports:
  #    - "2468:2468"
  #  volumes:
  #    - ${BASE_PATH}/cross-seed/config:/config
  #    - ${BASE_PATH}/qbittorrent/config/qBittorrent/BT_backup:/torrents:ro
  #    - ${MEDIA_SHARE}/cross-seed/current-cross-seeds:/cross-seeds
  #  command: daemon
  #  restart: unless-stopped

  #Kometa - used to create collections in plex. Example: "Most Popular Movies This Week", "Best of horror", etc.
  #
  #UPDATED: Replaces Plex Meta Manager which was deprecated in April 2024
  #Migration guide: https://kometa.wiki/en/latest/kometa/guides/rebrand/
  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    environment:
      - TZ=${TZ}
      #- KOMETA_OVERLAYS_ONLY=true #Tells Kometa to run overlays only
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_RUN=true #Runs Kometa Immediately
      #- KOMETA_RUN_LIBRARIES=Movies #Tells Kometa to process only a library called "Movies"
    volumes:
      - ${BASE_PATH}/kometa/config:/config
    restart: unless-stopped

  #Wizarr - Allows you to create a share link that you can send to users to invite them to your media server
  #Supports Plex, Jellyfin, Emby, Audiobookshelf, Romm, Komga and Kavita
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    ports:
      - 5690:5690
    volumes:
      - ${BASE_PATH}/wizarr/data/database:/data/database
    restart: unless-stopped

  #Dozzle - Used to easily view logs of any container in real time!
  #For historical logs/search, consider Loki + Grafana
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    restart: unless-stopped

  #Unpackerr - Used to unzip zipped files
  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - ${MEDIA_SHARE}:/share
      #- ${BASE_PATH}/unpackerr/config:/config
    restart: unless-stopped
    user: 1000:1000 #Needs to run as 1000
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need.
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      - UN_START_DELAY=1m
      #- UMASK=002
      - TZ=${TZ}
      #- UN_DEBUG=true
      # Sonarr Config
      - UN_SONARR_0_URL=http://${SERVER_IP}:8989
      - UN_SONARR_0_API_KEY=${SONARR_KEY}
      #- UN_SONARR_0_PATHS_0=/share/downloads/tv
      - UN_SONARR_0_TIMEOUT=10s
      #- UN_SONARR_0_PATHS_0=/share/downloads/tv
      # Radarr Config
      - UN_RADARR_0_URL=http://${SERVER_IP}:7878
      - UN_RADARR_0_API_KEY=${RADARR_KEY}
      #- UN_RADARR_0_PATHS_0=/share/downloads/movies
      - UN_RADARR_0_TIMEOUT=10s
      #- UN_RADARR_0_PATHS_0=/share/downloads/movies

  # Recyclarr - Used to sync Trash Guides config's to radarr and sonarr
  # Only accessible via command line! No GUI
  # Supports Radarr and Sonarr v4+
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: ${PUID}:${GUID}
    volumes:
      - ${BASE_PATH}/recyclarr/config:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  # ============================================
  # DASHBOARD
  # ============================================

  #Homepage - Modern dashboard for all your services
  #
  #https://gethomepage.dev/
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=10.10.11.201:3000,localhost:3000,homelab:3000
    volumes:
      - ${BASE_PATH}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/truenas/movies:/mnt/truenas/movies:ro
      - /mnt/truenas/config:/mnt/truenas/config:ro
    ports:
      - 3000:3000
    restart: unless-stopped

  # ============================================
  # ADULT CONTENT MANAGEMENT
  # ============================================

  #Whisparr - Automated adult content management (part of the Servarr family)
  #
  #Works like Radarr/Sonarr but for adult content
  #Integrates with Prowlarr for indexers
  #https://wiki.servarr.com/whisparr
  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    container_name: whisparr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/whisparr/config:/config
      - ${MEDIA_SHARE}:/share  # Full share access for hardlinking (downloads + xxx)
    ports:
      - 6969:6969
    restart: unless-stopped

  #Stash - Adult media organizer with metadata scraping
  #
  #Features: metadata scraping, scene detection, performer identification,
  #tagging system, duplicate detection, web-based streaming
  #https://stashapp.cc/
  stash:
    image: stashapp/stash:latest
    container_name: stash
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - ${BASE_PATH}/stash/config:/root/.stash
      - ${DOCKER_PATH}/stash/generated:/generated
      - ${DOCKER_PATH}/stash/metadata:/metadata
      - ${DOCKER_PATH}/stash/cache:/cache
      - ${MEDIA_SHARE}/xxx:/data  # Adult content library
    ports:
      - 9998:9999
    restart: unless-stopped
